# Generated by Django 4.1.7 on 2023-04-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_listing_category_listing_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='categories',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Readings', 'Readings'), ('Clothing', 'Clothing')], default=1, max_length=20),
        ),
    ]
