# Generated by Django 4.1.7 on 2023-04-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='categories',
            field=models.CharField(choices=[('books', 'Books'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home', 'Home'), ('sport', 'Sport')], default='books', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
