# Generated by Django 4.1.7 on 2023-04-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_categories_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.URLField(default='https://www.bing.com/images/search?view=detailV2&ccid=6wlQAeQK&id=69685E0F5569F4C371AEF301C82734EC4246C5D5&thid=OIP.6wlQAeQKg1j8meVb1yGnRgHaHa&mediaurl=https%3a%2f%2fimage.flaticon.com%2ficons%2fsvg%2f812%2f812953.svg&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.eb095001e40a8358fc99e55bd721a746%3frik%3d1cVGQuw0J8gB8w%26pid%3dImgRaw%26r%3d0&exph=512&expw=512&q=Broken+Thumbnail+Icons&simid=608028045153494391&FORM=IRPRST&ck=9F64E681E54249C4CC70BB52A6926104&selectedIndex=1&ajaxhist=0&ajaxserp=0', max_length=1000),
        ),
    ]
