# Generated by Django 4.2.5 on 2023-09-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0019_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="current_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
