# Generated by Django 4.2.5 on 2023-09-11 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0023_delete_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="bidders",
            field=models.ManyToManyField(
                default=[], related_name="bid_listings", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
